### ISSUE TITLE
Implement getter for DrivetrainDynamicReport_s

### ISSUE THREAD

**Issue by Dopp-IO** [hytech-racing/MCU#32]
Required for TC power limiting functionality. This data must be ticked into `torque_controller_mux`.

**Comment by RCMast3r** [comment]
I added in the getter here: https://github.com/hytech-racing/MCU/blob/master/lib/systems/include/DrivetrainSystem.tpp#L145

however, there is some slight config stuff we need to look at on the inverters to get the torques.

in the old version of code we just used the torque setpoint as our torque estimate however as I state here: 

https://github.com/hytech-racing/MCU/blob/master/lib/interfaces/include/InverterInterface.tpp#L93

we should be able to get the real torque output of the motors from the inverter by enabling a signal on the CAN bus.

additionally while we are looking at the inverter configs we need to get the id110 value for the current scaling for iq and id if we still want those so that we can get it data into regular Amperes.
